export const tickerMessages = [
  'NOW BOOKING Q1 & Q2 2026 — CORPORATE · DOCUMENTARY · LIVE EVENT',
  '30 YEARS BEHIND THE LENS. STILL ROLLING.',
  'AVAILABLE FOR SCREAM 7 PREMIERE COVERAGE — SERIOUS INQUIRIES ONLY — I WILL NOT BE GOING BACK TO WOODSBORO',
  '"BEST FREELANCE VIDEOGRAPHER IN THE TRI-STATE AREA" — GALE WEATHERS, PROBABLY',
  "NEW BLOG POST: WHY I'M NOT WATCHING SCREAM 7 (BUT I HOPE IT DOES WELL)",
  'REMINDER: KENNY DOES NOT DO FOUND FOOTAGE PROJECTS. STOP ASKING.',
] as const;

export const footerCredit = 'Site designed by someone who is definitely not Ghostface™';
